name: End-to-end tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image
        run: ./gradlew dockerBuild

      - name: Set up local environment and run e2e-tests
        run: |
          cd local
          make up
          sleep 15
          make e2e-tests