name: End-to-end tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build API Lambda
        run: ./gradlew buildLambdaZip

      - name: Build Docker image
        run: ./gradlew dockerBuild

      - name: Set up local environment and run e2e-tests
        run: |
          cd local
          make up
          sleep 40
          make e2e-tests