name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  end-to-end-tests:
    uses: ./.github/workflows/end-to-end-tests.yml

  verify-infra:
    runs-on: ubuntu-latest

    needs:
      - build
      - end-to-end-tests
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_REPO_IAM_ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Build Lambda
        run: ./gradlew buildLambdaZip

      - name: Run plan
        working-directory: infra
        run: |
          terraform init
          terraform plan \
            -lock=true \
            -refresh=true